//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2SeriosuGame.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestParameters
    {
        public int IdTestParameters { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> Rounds { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Loss { get; set; }
        public Nullable<int> Time_Used { get; set; }
        public Nullable<double> AVG_Clicks { get; set; }
    }
}
